- name: Website deploying
  hosts: webservers
  become: true
  tasks:
   - name: install repo
     yum: 
       name: epel-release 
       state: latest
   - name: upgrade all packages
     yum: 
       name: '*' 
       state: latest
   - name: install nginx
     yum: 
       name: nginx
       state: latest
   - name: Enable and start nginx 
     ansible.builtin.systemd:
       name: nginx
       state: started
       enabled: yes
   - name: install wget
     yum: 
       name: wget
       state: latest