- name: Website deploying
  hosts: webservers
  become: true
  tasks:
    - name: install repo
      yum: 
        name: epel-release 
        state: latest
    - name: upgrade all packages
      yum: 
        name: '*' 
        state: latest
    - name: install nginx
      yum: 
        name: nginx
        state: latest
    - name: Enable and start nginx 
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
    - name: install wget
      yum: 
        name: wget
        state: latest
    - name: install unzip
      yum: 
         name: unzip
         state: latest
    - name: Unarchive site
      ansible.builtin.unarchive:
        src: https://slava.fvds.ru/packages/kt_freebie_aironepage.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: change root
      shell: "sed -i 's%root.*%root \/usr\/share\/nginx\/html\/aironepage\/HTML;%'  /etc/nginx/nginx.conf && \
      systemctl restart nginx"