- name: Prometheus
  hosts: prometheus
  become: true
  tasks:
    - name: install repo
      yum: 
        name: epel-release 
        state: latest
    - name: upgrade all packages
      yum: 
        name: '*' 
        state: latest
    - name: install wget
      yum: 
        name: wget
        state: latest
    - name: Add the user 'prometheus'
      ansible.builtin.user:
        name: prometheus
        shell: /bin/false
        create_home: false
    - name: Wget prometheus
      ansible.builtin.shell: wget https://github.com/prometheus/prometheus/releases/download/v2.37.5/prometheus-2.37.5.linux-amd64.tar.gz

    - name: install prometheus
      ansible.builtin.shell: | 
        tar xvfz prometheus-2.37.5.linux-amd64.tar.gz && \
        cd prometheus-2.37.5.linux-amd64 && \
        mkdir /etc/prometheus && \
        mkdir /var/lib/prometheus && \
        cp ./prometheus promtool /usr/local/bin/ && \
        cp -R ./console_libraries /etc/prometheus && \
        cp -R ./consoles /etc/prometheus && \
        cp ./prometheus.yml /etc/prometheus && \
        chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus && \
        chown prometheus:prometheus /usr/local/bin/prometheus && \
        chown prometheus:prometheus /usr/local/bin/promtool

    - name: Creating an empty prometheus.service file
      file:
        path: /etc/systemd/system/prometheus.service
        state: touch
        owner: prometheus
        group: prometheus

    - name: Creating service prometheus.service
      blockinfile:
        path: /etc/systemd/system/prometheus.service
        block: |
          [Unit]
          Description=Prometheus Service Netology Lesson 9.4
          After=network.target
          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries
          ExecReload=/bin/kill -HUP $MAINPID Restart=on-failure
          [Install]
          WantedBy=multi-user.target

    - name: Enable and start prometheus 
      ansible.builtin.systemd:
          name: prometheus
          state: started
          enabled: yes

    - name: Download node_exporter
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz

    - name: Extract node_exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes
        extra_opts:
        - '-z' 
    - name: create dir 
      ansible.builtin.file:
        path: /etc/prometheus/node-exporter
        state: directory
    - name: install node_exporter
      ansible.builtin.shell: |
        cp /tmp/node_exporter-1.5.0.linux-amd64/* /etc/prometheus/node-exporter/ && \ 
        chown -R prometheus:prometheus /etc/prometheus/node-exporter/
    - name: Creating an empty file
      file:
        path: /etc/systemd/system/node-exporter.service
        state: touch
        owner: prometheus
        group: prometheus
    - name: Creating service
      blockinfile:
        path: /etc/systemd/system/node-exporter.service
        block: |
          [Unit]
          Description=Node Exporter Lesson 9.4
          After=network.target
          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/etc/prometheus/node-exporter/node_exporter
          [Install]
          WantedBy=multi-user.target
    - name: Enable and start node_exporter 
      ansible.builtin.systemd:
          name: node-exporter
          state: started
          enabled: yes

    - name: install prometheus
      ansible.builtin.shell: |
        sed -i 's/scrape_interval:.*/scrape_interval: 5s/' /etc/prometheus/prometheus.yml && \
        sed -i 's/targets:.*/targets: ['localhost:9090', 'localhost:9100']/' /etc/prometheus/prometheus.yml
    - name: Enable and start prometheus 
      ansible.builtin.systemd:
            name: prometheus
            state: restarted



- name: Web-server node exporter
  hosts: webservers
  become: true
  tasks:
    - name: Add the user 'prometheus'
      ansible.builtin.user:
        name: prometheus
        shell: /bin/false
        create_home: false
    - name: Download node_exporter
      ansible.builtin.get_url:
          url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
          dest: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
    - name: Extract node_exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes
        extra_opts:
        - '-z' 
    - name: create dir 
      ansible.builtin.file:
        path: /etc/prometheus/node-exporter
        state: directory
    - name: install node_exporter
      ansible.builtin.shell: |
        cp /tmp/node_exporter-1.5.0.linux-amd64/* /etc/prometheus/node-exporter/ &&\
        chown -R prometheus:prometheus /etc/prometheus/node-exporter/
    - name: Creating an empty file
      file:
            path: /etc/systemd/system/node-exporter.service
            state: touch
            owner: prometheus
            group: prometheus
    - name: Creating service 
      blockinfile:
          path: /etc/systemd/system/node-exporter.service
          block: |
            [Unit]
            Description=Node Exporter Lesson 9.4
            After=network.target
            [Service]
            User=prometheus
            Group=prometheus
            Type=simple
            ExecStart=/etc/prometheus/node-exporter/node_exporter
            [Install]
            WantedBy=multi-user.target
    - name: Enable and start node_exporter 
      ansible.builtin.systemd:
              name: node-exporter
              state: started
              enabled: yes


- name: Prometheus
  hosts: prometheus
  become: true
  tasks:
    - name: install prometheus
      ansible.builtin.shell: |
          sed -i 's/scrape_interval:.*/scrape_interval: 5s/' /etc/prometheus/prometheus.yml &&\
          sed -i 's/targets:.*/targets: ['localhost:9090', 'localhost:9100', {{ ip_int_webserver1 }}:9100, {{ip_int_webserver2}}:9100]/' /etc/prometheus/prometheus.yml
    - name: Enable and start prometheus 
      ansible.builtin.systemd:
              name: prometheus
              state: restarted