- name: test
  hosts: elastic
  become: true
  tasks:
   - name: hjsdhjhk
     shell: |
      /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana -b
     register: my_var

   - debug:
       msg: "{{ my_var }}"